#!/bin/bash

# Lead API Testing Script
# First, get your JWT token from the browser:
# Open DevTools -> Console -> Run: localStorage.getItem('activation_auth_token')

# Set your JWT token here (replace with actual token)
TOKEN="YOUR_JWT_TOKEN_HERE"
BASE_URL="http://localhost:8080/api"

echo "Lead API Testing Commands"
echo "========================="
echo "1. Replace YOUR_JWT_TOKEN_HERE with your actual token"
echo "2. Run the commands you want to test"
echo ""

echo "# Get all leads (paginated)"
echo "curl -X GET \"${BASE_URL}/leads?page=0&size=10\" \\"
echo "  -H \"Authorization: Bearer ${TOKEN}\" \\"
echo "  -H \"Content-Type: application/json\""
echo ""

echo "# Get leads for specific activation"
echo "curl -X GET \"${BASE_URL}/leads/activation/1\" \\"
echo "  -H \"Authorization: Bearer ${TOKEN}\" \\"
echo "  -H \"Content-Type: application/json\""
echo ""

echo "# Create a new lead"
echo "curl -X POST \"${BASE_URL}/leads\" \\"
echo "  -H \"Authorization: Bearer ${TOKEN}\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"name\": \"John\","
echo "    \"surname\": \"Doe\","
echo "    \"email\": \"john.doe@example.com\","
echo "    \"phone\": \"+1234567890\","
echo "    \"customerGender\": \"MALE\","
echo "    \"ageGroup\": \"BETWEEN_26_35\","
echo "    \"customerType\": \"SHOPPER\","
echo "    \"optedIn\": true,"
echo "    \"whatsAppOptedIn\": false,"
echo "    \"repeatPurchaseIntent\": \"YES\","
echo "    \"activationId\": 1"
echo "  }'"
echo ""

echo "# Search leads"
echo "curl -X GET \"${BASE_URL}/leads/search?searchTerm=john\" \\"
echo "  -H \"Authorization: Bearer ${TOKEN}\" \\"
echo "  -H \"Content-Type: application/json\""
echo ""

echo "# Get opted-in leads"
echo "curl -X GET \"${BASE_URL}/leads/opted-in\" \\"
echo "  -H \"Authorization: Bearer ${TOKEN}\" \\"
echo "  -H \"Content-Type: application/json\""
echo ""

echo "# Get WhatsApp opted-in leads"
echo "curl -X GET \"${BASE_URL}/leads/whatsapp-opted-in\" \\"
echo "  -H \"Authorization: Bearer ${TOKEN}\" \\"
echo "  -H \"Content-Type: application/json\""
echo ""

echo "# Get lead statistics"
echo "curl -X GET \"${BASE_URL}/leads/statistics\" \\"
echo "  -H \"Authorization: Bearer ${TOKEN}\" \\"
echo "  -H \"Content-Type: application/json\""
echo ""

echo "# Export all leads as CSV"
echo "curl -X GET \"${BASE_URL}/leads/export\" \\"
echo "  -H \"Authorization: Bearer ${TOKEN}\" \\"
echo "  -o all_leads.csv"
echo ""

echo "# Export all leads as Excel"
echo "curl -X GET \"${BASE_URL}/leads/export?format=xlsx\" \\"
echo "  -H \"Authorization: Bearer ${TOKEN}\" \\"
echo "  -H \"Accept: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet\" \\"
echo "  -o all_leads.xlsx"
echo ""

echo "# Export leads for specific activation (using dedicated endpoint)"
echo "curl -X GET \"${BASE_URL}/leads/export/activation/1\" \\"
echo "  -H \"Authorization: Bearer ${TOKEN}\" \\"
echo "  -o activation_1_leads.csv"
echo ""

echo "# Export leads for specific activation as Excel (using dedicated endpoint)"
echo "curl -X GET \"${BASE_URL}/leads/export/activation/1?format=xlsx\" \\"
echo "  -H \"Authorization: Bearer ${TOKEN}\" \\"
echo "  -o activation_1_leads.xlsx"
echo ""

echo "# Export leads for specific activation as CSV (legacy query param method)"
echo "curl -X GET \"${BASE_URL}/leads/export?activationId=1&format=csv\" \\"
echo "  -H \"Authorization: Bearer ${TOKEN}\" \\"
echo "  -H \"Accept: text/csv\" \\"
echo "  -o activation_1_leads_legacy.csv"
echo ""

echo "# Get specific lead by ID"
echo "curl -X GET \"${BASE_URL}/leads/1\" \\"
echo "  -H \"Authorization: Bearer ${TOKEN}\" \\"
echo "  -H \"Content-Type: application/json\""
echo ""

echo "# Update a lead"
echo "curl -X PUT \"${BASE_URL}/leads/1\" \\"
echo "  -H \"Authorization: Bearer ${TOKEN}\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{"
echo "    \"name\": \"John\","
echo "    \"surname\": \"Smith\","
echo "    \"email\": \"john.smith@example.com\","
echo "    \"phone\": \"+1234567890\","
echo "    \"customerGender\": \"MALE\","
echo "    \"ageGroup\": \"BETWEEN_26_35\","
echo "    \"customerType\": \"SHOPPER\","
echo "    \"optedIn\": true,"
echo "    \"whatsAppOptedIn\": true,"
echo "    \"repeatPurchaseIntent\": \"YES\""
echo "  }'"
echo ""

echo "# Delete a lead"
echo "curl -X DELETE \"${BASE_URL}/leads/1\" \\"
echo "  -H \"Authorization: Bearer ${TOKEN}\""
echo ""